# Generated by Django 4.0.4 on 2022-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('website', models.URLField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Streaming Platform',
                'verbose_name_plural': 'Streaming Platforms',
            },
        ),
    ]
