# Generated by Django 4.0.4 on 2022-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_ratings',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of ratings'),
        ),
    ]
